name: 'Deploy to Azure'
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: '🧑‍🦱 Azure login'
        uses: azure/login@v2
        with:
          client-id: 93167fe8-1402-4d99-aaf9-8c96e5e64e12
          tenant-id: b1a8ac21-915f-4351-a075-b30346a974af
          subscription-id: 96ff2809-c950-4a50-9eb6-f26f23d32735

      - name: 'Deploy to Azure'
        run: |
          az deployment sub create \
            --name Deployment-$(date +"%Y-%m-%dT%H-%M-%S") \
            --template-file resource-group.bicep \
            --location westeurope \
            --parameters \
                location=westeurope \
                stage=dev

      - name: 'Deploy Storage to Azure'
        run: |
          az deployment group create \
          --name Deployment-$(date +'%Y-%m-%dT%H-%m-%S') \
          --template-file storage.bicep \
          --resource-group awinds-azure-workshop-dev \
          --parameters \
              location=$LOCATION \
              stage=dev